package com.iispl.enums;

public enum ChequeValidationEnum {

    VALIDATION_SUCCESS,
    INVALID_CHEQUE_AMOUNT,
    INVALID_CHEQUE_NUMBER,
    INVALID_ACCOUNT_NUMBER,
    INVALID_DRAWER_NAME,
    INVALID_PRESENTING_BANK,
    INVALID_CLEARING_ZONE,
    INVALID_CHEQUE_DATE,
    INVALID_PRESENTED_DATE,
    INVALID_PRIORITY,
    INVALID_STATUS,
    HIGH_PRIORITY_CHEQUE,
    DUPLICATE_CHEQUE_NUMBER,
    INVALID_ACCOUNT_NUMBER_LENGTH

}